### ISSUE TITLE
搜索组件异步加载导致丢失输入字符

### ISSUE THREAD

**Issue by 599316527** [ecomfe/veui-docs#14]
## 问题

页面展现后搜索框就可以输入，但此时搜索组件未加载完成，输入无效。

## 复现

如下视频所示，页面打开后输入 `number` ，`nu` 触发两个  js error ，UI无反馈，然后搜索组件出现，展现 `mber` 无结果。

https://user-images.githubusercontent.com/1331413/147339000-d109dfa5-6fee-466b-a22d-b059899257b0.mp4

**Comment by Justineo** [comment]
Fixed in b22b1cf.
