### ISSUE TITLE
Demo样式：Button 边距问题

### ISSUE THREAD

**Issue by 599316527** [ecomfe/veui-docs#15]
![image](https://user-images.githubusercontent.com/1331413/148540362-baa76036-07ff-4d7e-a92d-c2784e2bbf38.png)

**Comment by Justineo** [comment]
应该还是SSR样式顺序的问题

**Comment by Justineo** [comment]
看了一下是 docs 升级的时候不知道为啥没有安装到 veui 最新版本，theme 却更新到最新了。升级了一下没问题了。
