### ISSUE TITLE
实时编辑 应该有个最小化 按钮

### ISSUE THREAD

**Issue by 599316527** [ecomfe/veui-docs#16]
现在只有一个退出，编辑到一半想要看下 props, slots 定义就比较麻烦。

**Comment by Justineo** [comment]
Implemented in https://github.com/ecomfe/veui-docs/commit/1aebcf32ab2f58e9f57f64bc89bca2444d22a649.

**Comment by 599316527** [comment]
即使收缩了之后，切换组件还是会关掉编辑器。而编辑 Tabs 时要看下 Tab 的 props 就不行了 😂

**Comment by Justineo** [comment]
这个升级成本就比较高了，切换 Tab 的 props 就先 <kbd>⌘</kbd> + 点击开新标签页吧。
